name: Node.js Package
on:
  push:
    branches:
      - main
jobs:
  publish-package:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/

      - name: Set NPM Registry
        run: npm set registry https://npm.pkg.github.com/zkladder

      - name: Inject Personal Access Token
        env:
          ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: npm set //npm.pkg.github.com/:_authToken $ACCESS_TOKEN

      - run: npm ci
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
